### ISSUE TITLE
archive command ignores directories in isolate file

### ISSUE THREAD

**Issue by mithro** [luci/luci-go#14]
My `out/Release/webkit_tests.isolate` has the following in it;
```
                         'pyproto/google/protobuf/message_factory.py',
                         'pyproto/google/protobuf/reflection.py',
                         'pyproto/google/protobuf/service.py',
                         'pyproto/google/protobuf/service_reflection.py',
                         'pyproto/google/protobuf/text_format.py',
                         'resource_provider/manifest.json',
                         'resource_provider/resource_provider.mojo',
                         'resources/inspector/',
                         'shell/manifest.json',
                         'snapshot_blob.bin',
```

The Python archive command correctly uploads all the files under `resources/inspector` but the go version does not.

Go isolate archive output - https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=c0a953397e036ee5e7599963f8acbd9f1f113d52
Python isolate archive output - https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=9f6735ced7291dbd950279a6ecd8a434fb724ac3

**Comment by erikus** [comment]
@maruel

**Comment by maruel** [comment]
@shishkander can you look? Probably worth discussing over IM.

**Comment by shishkander** [comment]
0 days since I've been investigating this "bug". Actually both work correctly. Easy to verify - download them locally and see for yourself:

    ./isolateserver.py` download -s c0a953397e036ee5e7599963f8acbd9f1f113d52 -I https://isolateserver.appspot.com -t out_c0a953397e036ee5e7599963f8acbd9f1f113d52
    ./isolateserver.py download -s 9f6735ced7291dbd950279a6ecd8a434fb724ac3 -I https://isolateserver.appspot.com -t out_9f6735ced7291dbd950279a6ecd8a434fb724ac3
    du -hs out_*
    # 758340  out_9f6735ced7291dbd950279a6ecd8a434fb724ac3
    # 758340  out_c0a953397e036ee5e7599963f8acbd9f1f113d52

The isolated file produced by Go has an extra include section [764f2e35958a7a4443af71dfb7b785e6f2ea5a3f](https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=764f2e35958a7a4443af71dfb7b785e6f2ea5a3f) which actually contains the seemingly missing directory.

*On the bright side, I've learned how to bootstrap our go env on a super slow and crappy WiFi while travelling, and also how to compare isolated trees without downloading their contents.*
