### ISSUE TITLE
multiple errors when installing luci-go

### ISSUE THREAD

**Issue by jimbojetlag** [luci/luci-go#32]
I just wanted to update luci-go, and now this dependency is broken:

```
# github.com/luci/luci-go/common/system/terminal
github.com/luci/luci-go/common/system/terminal/util_appengine.go:10: IsTerminal redeclared in this block
	previous declaration at github.com/luci/luci-go/common/system/terminal/util.go:19
# github.com/luci/luci-go/logdog/client/annotee/executor
github.com/luci/luci-go/logdog/client/annotee/executor/executor.go:78: undefined: exec.CommandContext
# github.com/luci/luci-go/grpc/discovery
github.com/luci/luci-go/grpc/discovery/service.pb.go:81: undefined: grpc.SupportPackageIsVersion3
```

**Comment by riannucci** [comment]
I think this is due to the recent update to go 1.7 (at least the CommandContext one is).

The SupportPackageIsVersion3 error probably has to do with the version of the protobuf library and the generated proto files. I suspect that your version of the grpc package and/or the proto package is too old/new.

Here is the deps file that we use when we're building with luci-go: https://chromium.googlesource.com/infra/infra/+/master/go/deps.lock . Hopefully it provides some insight.

**Comment by riannucci** [comment]
(those are [glide](https://github.com/Masterminds/glide) dependency files BTW)

**Comment by jimbojetlag** [comment]
Thanks, I'm not using a Go package manager (waiting for an official support by 2050s :).

I still get the installation errors after `rm -rdf github.com/luci` in both src and pkg directories. Am I missing dependencies external to luci?

Oh, and I'm using gae `goapp` to install luci-go, the latest version was released yesterday:

```
$ goapp version
go version go1.6.3 (appengine-1.9.46) darwin/amd64

$ goapp get -u github.com/luci/luci-go/...
# github.com/luci/luci-go/common/system/terminal
github.com/luci/luci-go/common/system/terminal/util_appengine.go:10: IsTerminal redeclared in this block
	previous declaration at github.com/luci/luci-go/common/system/terminal/util.go:19
# github.com/luci/luci-go/grpc/discovery
github.com/luci/luci-go/grpc/discovery/service.pb.go:81: undefined: grpc.SupportPackageIsVersion3
# github.com/luci/luci-go/logdog/client/annotee/executor
github.com/luci/luci-go/logdog/client/annotee/executor/executor.go:78: undefined: exec.CommandContext
```

**Comment by riannucci** [comment]
Ah, yeah I know what you mean. Really hoping there's a solid official dependency management strategy soon... :/.

So goapp is still (unfortunately) stuck in the past for now. Since luci-go contains both appengine stuff and non-appengine stuff, we had to upgrade to 1.7 for the non-appengine stuff (for performance reasons). Can you try just using `goapp get -d` to just download luci-go and then building your apps? That would let you discover the dependencies your program actually has. I suspect that `goapp get` is attempting to compile every single package in luci-go, which isn't necessary.

For the grpc errors I think that may mean that we need to update our grpc version and generate a new one.  Try cd'ing into your grpc package and doing a git checkout of the version we have in our pin files (which looks like 396f8ba2a6b9039070f4ff97561f5e408828fccd).

The CommandContext one should be safe to ignore; that only applies to CLI apps.

I'm not sure about the IsTerminal error though... util.go and util_appengine.go should be mutually exclusive :(. They should never build at the same time. That said, I suspect that common/system/terminal is also not a package that any of your apps would transitively depend on.

**Comment by jimbojetlag** [comment]
Thank you! `google.golang.org/genproto` and `google.golang.org/grpc` dependencies were the problem.

Unfortunately, `goapp install github.com/luci/luci-go/...` still fails with:

```
# github.com/luci/luci-go/common/system/terminal
github.com/luci/luci-go/common/system/terminal/util_appengine.go:10: IsTerminal redeclared in this block
previous declaration at github.com/luci/luci-go/common/system/terminal/util.go:19
# github.com/luci/luci-go/logdog/client/annotee/executor
github.com/luci/luci-go/logdog/client/annotee/executor/executor.go:78: undefined: exec.CommandContext
```

The reason I'm trying to `go install` is that goapp is stuck in 1.6, and compilation during development is really slow.

While 1.7 will shorten the compilation time, it feels like a lot of irrelevant dependencies get compiled. I really use luci-go for its amazing server package, it comes with a lot of sensible defaults, and also for its grpc generator . Hopefully, you guys will be convinced that the general parts of luci-go could be moved to a separate package to avoid problems like this (#30) :)

Thanks again for your prompt help.

**Comment by riannucci** [comment]
Happy to help!

I think you can `goapp install` the packages that you need (in fact, if you `goapp install` your personal server code, I think it will transitively install all the packages that it depends on as well).
